# Generated by Django 4.1.7 on 2023-02-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Brand name')),
                ('image', models.ImageField(upload_to='brand_logos/%Y/%m/%d/', verbose_name='Logo')),
                ('segment', models.CharField(choices=[('eco', 'Economy'), ('premium', 'Premium'), ('super-premium', 'Super premium')], max_length=30, verbose_name='Price segment')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Filter group title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Title in URL')),
            ],
            options={
                'verbose_name': 'Filter group',
                'verbose_name_plural': 'Filter groups',
            },
        ),
        migrations.CreateModel(
            name='FilterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filter name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Name in URL')),
                ('filter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.filtergroup', verbose_name='Filter group')),
            ],
            options={
                'verbose_name': 'Filter item',
                'verbose_name_plural': 'Filter items',
            },
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product type')),
                ('url_name', models.CharField(default='-', max_length=30, verbose_name='Product type in URL')),
                ('image', models.ImageField(blank=True, upload_to='types_of_prod_img/%Y/%m/%d/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('vendor_code', models.CharField(max_length=255, unique=True, verbose_name='Vendor code')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Product description')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('age_of_animal', models.CharField(blank=True, max_length=255, verbose_name='Animal age')),
                ('source_of_protein', models.CharField(blank=True, max_length=255, verbose_name='Protein source')),
                ('is_hit', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.brand', verbose_name='Brand')),
                ('filter_items', models.ManyToManyField(to='shop_app.filteritem', verbose_name='Filters')),
                ('type_of_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.typeofproduct', verbose_name='Product type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Weight (kg)')),
                ('current_price', models.IntegerField(verbose_name='Current price (USD)')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Old price in USD (if a discount is active)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='Product for this packing')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
            },
        ),
        migrations.AddField(
            model_name='filtergroup',
            name='type_of_products',
            field=models.ManyToManyField(to='shop_app.typeofproduct', verbose_name='Product types for this filter group'),
        ),
        migrations.AddField(
            model_name='brand',
            name='type_of_products',
            field=models.ManyToManyField(to='shop_app.typeofproduct', verbose_name='Product types made by the brand'),
        ),
    ]
