# Generated by Django 4.1.7 on 2023-03-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_productincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='product_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product'),
        ),
    ]
