# Generated by Django 4.1.7 on 2023-03-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_productincart_product_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='product_pk',
            new_name='product',
        ),
    ]
