# Generated by Django 4.1.7 on 2023-03-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_rename_product_pk_productincart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='packing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.packing'),
        ),
    ]
