# Generated by Django 6.0.4 on 2026-04-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_productincart_packing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='filtergroup',
            options={'verbose_name': 'Filter group', 'verbose_name_plural': 'Filter groups'},
        ),
        migrations.AlterModelOptions(
            name='filteritem',
            options={'verbose_name': 'Filter item', 'verbose_name_plural': 'Filter items'},
        ),
        migrations.AlterModelOptions(
            name='packing',
            options={'verbose_name': 'Packing', 'verbose_name_plural': 'Packings'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'Cart item', 'verbose_name_plural': 'Cart items'},
        ),
        migrations.AlterModelOptions(
            name='typeofproduct',
            options={'verbose_name': 'Product type', 'verbose_name_plural': 'Product types'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brand_logos/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='segment',
            field=models.CharField(choices=[('eco', 'Economy'), ('premium', 'Premium'), ('super-premium', 'Super premium')], max_length=30, verbose_name='Price segment'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='type_of_products',
            field=models.ManyToManyField(to='shop_app.typeofproduct', verbose_name='Product types made by the brand'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Title in URL'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Filter group title'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='type_of_products',
            field=models.ManyToManyField(to='shop_app.typeofproduct', verbose_name='Product types for this filter group'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='filter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.filtergroup', verbose_name='Filter group'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Filter name'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Name in URL'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='current_price',
            field=models.IntegerField(verbose_name='Current price (USD)'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Old price in USD (if a discount is active)'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='Product for this packing'),
        ),
        migrations.AlterField(
            model_name='packing',
            name='weight',
            field=models.IntegerField(verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_of_animal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Animal age'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_items',
            field=models.ManyToManyField(blank=True, to='shop_app.filteritem', verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Hit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_of_protein',
            field=models.CharField(blank=True, max_length=255, verbose_name='Protein source'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.typeofproduct', verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Vendor code'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='types_of_prod_img/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Product type'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='url_name',
            field=models.CharField(default='-', max_length=30, verbose_name='Product type in URL'),
        ),
    ]
